name: E2E on Chrome
on:
  push:
    branches:
      - master
      - develop
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    # let's make sure our tests pass on Chrome browser
    name: E2E on Chrome
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.1.1
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-${{ hashFiles('package-lock.json') }}
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: CI=false npm run-script build
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          # start with test instrument
          start: npm run start-cy
          wait-on: "http://127.0.0.1:3000"
          # wait for 2 minutes for the server to respond
          wait-on-timeout: 120
      - name: Generate Test Coverage report
        run: npm run coverage
      - name: Commit Test Coverage
        run: |
          git config --global user.email <%= githubCommitEmail %>
          git config --global user.name "GitHub Action"
          git add coverage/badge-branches.svg
          git add coverage/badge-functions.svg
          git add coverage/badge-lines.svg
          git add coverage/badge-statements.svg
          git commit -am "auto-commit: update test coverage"
          git push
